Repository TeamSparker/Spark-Server, pull requests merged in 2022-03, with the labels that each got.

#227 [FEAT] 게시글 신고하기 및 보관함 대표사진 변경
  functions/api/routes/feed/feedReportPOST.js
  functions/api/routes/feed/index.js
  functions/api/routes/myroom/index.js
  functions/api/routes/myroom/myroomThumbnailPATCH.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/report.js
  functions/db/room.js
  functions/middlewares/slackAPI.js
Labels: Enhancement ✨, POST 💜, PATCH 💚, 🐱 설희, ⭐️Release Fighting⭐️

#230 [REFACTOR] 빨콩 표시 조건 수정
  functions/api/routes/notice/noticeNewGET.js
  functions/db/notice.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#231 [FEAT] 다이얼로그 알림 (성공,실패,생명감소 알림)
  functions/api/routes/room/index.js
  functions/api/routes/room/roomDetailGET.js
  functions/api/routes/room/roomListGET.js
  functions/api/routes/room/roomReadPATCH.js
  functions/constants/responseMessage.js
  functions/db/db.js
  functions/db/dialog.js
  functions/db/index.js
  functions/db/room.js
  functions/scheduler/funcs.js
Labels: Enhancement ✨, 🐱 설희, ⭐️Release Fighting⭐️

#238 [UPDATE] 이미 신고한 피드 status code 변경
  functions/api/routes/feed/feedReportPOST.js
  functions/constants/statusCode.js
Labels: 🐱 설희, Refactor🔪

#254 [FIX] 알림 service, active 구분 1차 릴리즈에 맞게 수정
  functions/constants/alarmMessage.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️

#241 [FEAT] 생명감소 알림 다이얼로그 어제 알림만 조회되게 수정
  functions/db/dialog.js
  functions/db/schedule.js
  functions/scheduler/funcs.js
Labels: 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#242 [FEAT] 알림 조회 API 데이터 추가
  functions/api/routes/notice/active/activeGET.js
  functions/api/routes/notice/service/serviceGET.js
  functions/db/notice.js
Labels: 🦋 영권, Enhancement ✨, High-Priority 🚨, ⭐️Release Fighting⭐️

#249 [FEAT] feedLikePOST notification 연동
  functions/api/routes/feed/feedLikePOST.js
  functions/constants/alarmMessage.js
  functions/db/notice.js
  functions/db/room.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#256 [FEAT] 중복 신고 가능하도록 수정
  functions/api/routes/feed/feedReportPOST.js
  functions/constants/responseMessage.js
Labels: Enhancement ✨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#257 [FEAT] 피드 모아보기에서 자신의 record인지 여부 추가
  functions/api/routes/feed/feedGET.js
Labels: Enhancement ✨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#259 [CHORE] 쿼리문에서 join(',') -> join()
  functions/db/dialog.js
  functions/db/record.js
Labels: 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#261 [FEAT] 습관방 리스트 모아보기에 isUploaded 항목 추가
  functions/api/routes/room/roomListGET.js
  functions/db/dialog.js
  functions/db/record.js
  functions/db/room.js
Labels: Enhancement ✨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#270 [HOTFIX] remove undefined user at Error log
  functions/api/routes/auth/authDoorbellGET.js
Labels: bug 🧨, 🦋 영권, High-Priority 🚨, 🚨 ISSUE 🚨

#273 [FIX] Error log에 user nickname 정보 추가
  functions/api/routes/feed/feedGET.js
  functions/api/routes/feed/feedLikePOST.js
  functions/api/routes/feed/feedReportPOST.js
  functions/api/routes/myroom/myroomGET.js
  functions/api/routes/myroom/myroomRoomGET.js
  functions/api/routes/myroom/myroomThumbnailPATCH.js
  functions/api/routes/notice/active/activeGET.js
  functions/api/routes/notice/noticeNewGET.js
  functions/api/routes/notice/noticeSettingGET.js
  functions/api/routes/notice/noticeSettingPATCH.js
  functions/api/routes/notice/service/serviceGET.js
  functions/api/routes/room/roomCodeGET.js
  functions/api/routes/room/roomDELETE.js
  functions/api/routes/room/roomDetailGET.js
  functions/api/routes/room/roomEnterPOST.js
  functions/api/routes/room/roomListGET.js
  functions/api/routes/room/roomOutDELETE.js
  functions/api/routes/room/roomPOST.js
  functions/api/routes/room/roomPurposePATCH.js
  functions/api/routes/room/roomReadPATCH.js
  functions/api/routes/room/roomRecordPOST.js
  functions/api/routes/room/roomStartPOST.js
  functions/api/routes/room/roomStatusPOST.js
  functions/api/routes/room/roomWaitingGET.js
  functions/api/routes/room/roomWaitingMemberGET.js
  functions/api/routes/room/sparkPOST.js
  functions/api/routes/user/userProfileGET.js
  functions/api/routes/user/userProfilePATCH.js
Labels: 🦋 영권, Enhancement ✨

#275 [FEAT] uploadImage middleware에 Slack API 연동
  functions/middlewares/uploadImage.js
Labels: 🦋 영권, Enhancement ✨

#277 [FEAT] uploadImage 미들웨어 파일확장자 exception에 logger 추가
  functions/api/routes/room/roomListGET.js
  functions/middlewares/uploadImage.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️

#281 [ISSUE] 습관방에 혼자 참여한 경우 인증 오류
  functions/api/routes/room/roomRecordPOST.js
  functions/api/routes/room/roomStatusPOST.js
Labels: bug 🧨, 🦋 영권, Enhancement ✨

#282 [FEAT] 리마인드 푸시알림 추가
  functions/constants/alarmMessage.js
  functions/db/index.js
  functions/db/record.js
  functions/db/remind.js
  functions/db/room.js
  functions/db/user.js
  functions/index.js
  functions/scheduler/funcs.js
  functions/scheduler/scheduler.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️

#284 [HOTFIX] 퇴장한 습관방 사진 모아보기 block
  functions/api/routes/myroom/myroomRoomGET.js
  functions/db/room.js
Labels: bug 🧨, 🦋 영권, Enhancement ✨, High-Priority 🚨, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#297 [Issue] scheduling 왜 제멋대로 돌아감?
  functions/scheduler/scheduler.js
Labels: bug 🧨, 🦋 영권, 🚨 ISSUE 🚨

#285 [FIX] notification 최근 7일 계산 방식 변경
  functions/db/notice.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#301 [HOTFIX] Scheduling 시간 조건으로 인해 작동 안함
  functions/scheduler/scheduler.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#302 [FEAT] 로그아웃 API 구현
  functions/api/routes/auth/authSignOutPOST.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: 🦋 영권, Enhancement ✨, POST 💜, ⭐️Release Fighting⭐️

#304 [FIX] 스케줄링 작업에서 이미 삭제된 방 제외처리
  functions/db/room.js
  functions/scheduler/funcs.js
Labels: bug 🧨, High-Priority 🚨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#305 [FEAT] 회원탈퇴
  functions/api/routes/auth/authUserDELETE.js
  functions/api/routes/auth/index.js
  functions/constants/responseMessage.js
  functions/db/room.js
  functions/db/user.js
Labels: DELETE ❤️‍🔥, Enhancement ✨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#306 [FIX] 보관함 카드 모아보기 날짜 계산방식 수정
  functions/api/routes/myroom/myroomGET.js
Labels: bug 🧨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#307 [FIX] 생명감소 다이얼로그 알림 방식 수정
  functions/api/routes/room/roomDetailGET.js
  functions/db/dialog.js
Labels: bug 🧨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#309 [FIX] 회원탈퇴 라우터 수정 + 이미 탈퇴한 회원 check 미들웨어행
  functions/api/routes/auth/index.js
  functions/middlewares/auth.js
Labels: bug 🧨, High-Priority 🚨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#310 [FIX] 회원탈퇴 버그 픽스
  functions/api/routes/auth/authUserDELETE.js
Labels: bug 🧨, High-Priority 🚨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#315 [FIX] 생명감소 다이얼로그 오늘 다이얼로그 조회안되는 버그 수정
  functions/db/dialog.js
Labels: bug 🧨, High-Priority 🚨, 🐱 설희, ⭐️Release Fighting⭐️, 🚨 ISSUE 🚨

#317 [Issue] Incorrect FCM Token
  functions/lib/pushAlarm.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#318 [FIX] 방 목록 순서 검토
  functions/api/routes/room/roomListGET.js
  functions/db/room.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, 🚨 ISSUE 🚨

#319 [FEAT] 푸시알림 끄고 켜기 적용
  functions/api/routes/room/roomRecordPOST.js
  functions/api/routes/room/roomStartPOST.js
  functions/api/routes/room/roomStatusPOST.js
  functions/api/routes/room/sparkPOST.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️

#323 [HOTFIX] getEntriesByRoomId 탈퇴한 유저 예외처리
  functions/db/room.js
Labels: bug 🧨, 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, 🚨 ISSUE 🚨
