Repository TeamSparker/Spark-Server, pull requests merged in 2022-09, with the labels that each got.

#427 fix: 10시 리마인드 중복 알림 방지 로직 구현
  functions/scheduler/funcs.js
Labels: High-Priority 🚨, 🐱 설희, Refactor🔪, 🚨 ISSUE 🚨

#429 [FEAT] 생명 타임라인 생성 및 감소 내용 추가
  functions/constants/lifeTimelineMessage.js
  functions/db/dialog.js
  functions/db/index.js
  functions/db/lifeTimeline.js
  functions/db/room.js
  functions/scheduler/funcs.js
Labels: 🦋 영권, TEST 🛠

#431 [FEAT] 생명 타임라인 조회 API 구현
  functions/api/routes/room/index.js
  functions/api/routes/room/roomTimelineGET.js
  functions/constants/lifeTimelineMessage.js
  functions/constants/responseMessage.js
  functions/db/lifeTimeline.js
Labels: 🦋 영권, GET 🧡, TEST 🛠

#434 [FEAT] 생명 타임라인 읽음 처리 기능 구현
  functions/api/routes/room/roomTimelineGET.js
  functions/constants/responseMessage.js
  functions/db/lifeTimeline.js
Labels: 🦋 영권, TEST 🛠
