Repository TeamSparker/Spark-Server, pull requests merged in 2022-10, with the labels that each got.

#436 [FIX] 생명 타임라인 조회 title에 감소 개수 반영
  functions/db/lifeTimeline.js
  functions/scheduler/funcs.js
Labels: 🦋 영권, Enhancement ✨, TEST 🛠

#437 [FIX] GET_FEED_SUCCESS 응답 메시지 오타
  functions/api/routes/feed/feedGET.js
  functions/constants/responseMessage.js
Labels: 🦋 영권, TEST 🛠

#439 [CHORE] funcs finally에 release log출력 삭제
  functions/scheduler/funcs.js
Labels: 🦋 영권

#441 [ISSUE] 존재하지 않는 방일때 생명 타임라인 조회 응답 없음
  functions/api/routes/myroom/myroomRoomGET.js
  functions/api/routes/myroom/myroomThumbnailListGET.js
  functions/api/routes/myroom/myroomThumbnailPATCH.js
  functions/api/routes/room/roomDetailGET.js
  functions/api/routes/room/roomTimelineGET.js
Labels: 🦋 영권, TEST 🛠

#443 [CHORE] roomDetailGET에 error 1번 예외처리 중복
  functions/api/routes/room/roomDetailGET.js
Labels: 🦋 영권, 🚨 ISSUE 🚨

#445 [REFACTOR] 생명 타임라인에 지난 날짜별 문자 처리 및 알림센터에도 적용
  functions/api/routes/notice/active/activeGET.js
  functions/api/routes/notice/service/serviceGET.js
  functions/api/routes/room/roomTimelineGET.js
  functions/lib/passedDayToStr.js
Labels: 🦋 영권, Refactor🔪

#447 [FEAT] 분기별 생명 충전 기능 추가
  functions/api/routes/room/roomTimelineGET.js
  functions/constants/lifeTimelineMessage.js
  functions/constants/termList.js
  functions/db/lifeTimeline.js
  functions/db/room.js
  functions/scheduler/funcs.js
Labels: 🦋 영권, Enhancement ✨, TEST 🛠

#448 [FEAT] 분기별 생명 충전 기능 추가
  functions/api/routes/room/roomStartPOST.js
  functions/scheduler/funcs.js
Labels: 🦋 영권, Enhancement ✨, TEST 🛠

#451 [HOTFIX] roomStartPOST API addFillTimelines 매개변수 오류 수정
  functions/api/routes/room/roomStartPOST.js
Labels: bug 🧨, 🦋 영권, TEST 🛠

#453 [REFACTOR] func와 roomStartPOST Insert 함수 호출에 배열 길이 조건 추가
  functions/api/routes/room/roomStartPOST.js
  functions/scheduler/funcs.js
Labels: 🦋 영권, Refactor🔪, TEST 🛠

#454 [FEAT] 습관방 상세 조회 API Update
  functions/api/routes/room/roomDetailGET.js
  functions/db/lifeTimeline.js
  functions/db/room.js
  functions/scheduler/funcs.js
Labels: 🦋 영권, Enhancement ✨, Refactor🔪, TEST 🛠

#456 [REFACTOR] 리마인드 푸시알림 업데이트 적용
  functions/constants/alarmMessage.js
  functions/scheduler/funcs.js
Labels: Enhancement ✨, High-Priority 🚨, 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪
