Repository TeamSparker/Spark-Server, pull requests merged in 2022-02, with the labels that each got.

#161 [FIX] 활동 알림 조회 Pagination 초기 값
  README.md
  functions/api/routes/notice/active/activeGET.js
  functions/db/notice.js
Labels: 🦋 영권, enhancement

#162 [FIX] 서비스 알림 조회 Pagination 초기 값
  functions/api/routes/notice/service/serviceGET.js
  functions/db/notice.js
Labels: 🦋 영권, enhancement

#164 [GET] /user/profile 프로필 조회 API 구현
  functions/api/routes/user/index.js
  functions/api/routes/user/userProfileGET.js
  functions/constants/responseMessage.js
Labels: 🦋 영권, Enhancement ✨, GET 🧡, ⭐️Release Fighting⭐️

#181 [FEAT] Token Expired, Invalid Response Message 추가
  functions/constants/responseMessage.js
Labels: bug 🧨, 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#179 [Issue] 보관함 리스트 불러오기 API 관련
  functions/api/routes/feed/feedGET.js
  functions/api/routes/myroom/myroomGET.js
  functions/api/routes/room/roomDetailGET.js
  functions/db/room.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#182 [refactor] 무한스크롤 쿼리파라미터 lastid->lastId 수정
  functions/api/routes/feed/feedGET.js
  functions/api/routes/myroom/myroomGET.js
  functions/api/routes/myroom/myroomRoomGET.js
  functions/api/routes/notice/active/activeGET.js
  functions/api/routes/notice/service/serviceGET.js
  functions/api/routes/room/roomListGET.js
  functions/constants/responseMessage.js
  functions/db/notice.js
Labels: 🐱 설희, ⭐️Release Fighting⭐️, Refactor🔪

#186 [FEAT] 습관방 리스트에, 쉴래요 여부 전달
  functions/api/routes/room/roomListGET.js
Labels: 🦋 영권, Enhancement ✨, High-Priority 🚨, ⭐️Release Fighting⭐️, Refactor🔪

#187 [FEAT] 습관방 리스트에 쉴래요 누른 인원수 포함해서 인증 인원으로 전달
  functions/api/routes/room/roomListGET.js
Labels: 🦋 영권, Enhancement ✨, High-Priority 🚨, ⭐️Release Fighting⭐️, Refactor🔪

#190 [REFACTOR] 대기방 상세 조회 참여자 정렬 기준 변경
  functions/api/routes/room/roomDetailGET.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#192 [FEAT] 고민중 2회 이상 불가능하게 처리
  functions/api/routes/room/roomStatusPOST.js
  functions/constants/responseMessage.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#194 [HOTFIX] roomListGET에 myStatus 값에서 CONSIDER 제거
  functions/api/routes/room/roomListGET.js
Labels: bug 🧨, 🦋 영권, Enhancement ✨, High-Priority 🚨, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#196 [REFACTOR] 습관방 상세 조회 참여자 정렬 기준 변경
  functions/api/routes/room/roomDetailGET.js
Labels: 🦋 영권, Enhancement ✨, High-Priority 🚨, Refactor🔪

#188 [REFACTOR] 대기방 나갈경우 hard delete
  functions/api/routes/room/roomOutPOST.js
  functions/constants/alarmMessage.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#206 [FEAT] Firebase Cloud Messaging with Image
  functions/lib/pushAlarm.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#203 [REFACTOR] Firebase Cloud Messaging Send Multicast
  functions/api/routes/room/roomRecordPOST.js
  functions/constants/alarmMessage.js
  functions/db/notice.js
  functions/db/room.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪, 🚨 ISSUE 🚨

#208 [REFACTOR] 대기방 및 습관방 나가기 API Request method 변경
  functions/api/routes/room/index.js
  functions/api/routes/room/roomOutPOST.js
Labels: 🦋 영권, ⭐️Release Fighting⭐️, Refactor🔪

#210 [FEAT] 대기방 삭제 API
  functions/api/routes/room/index.js
  functions/api/routes/room/roomDELETE.js
  functions/api/routes/room/roomOutDELETE.js
  functions/api/routes/room/roomRecordPOST.js
  functions/constants/alarmMessage.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, DELETE ❤️‍🔥, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪

#217 [FEAT] 푸시알림 그룹화 및 이미지 패싱
  functions/api/routes/room/roomRecordPOST.js
  functions/api/routes/room/roomStartPOST.js
  functions/api/routes/room/roomStatusPOST.js
  functions/api/routes/room/sparkPOST.js
  functions/constants/alarmMessage.js
  functions/lib/pushAlarm.js
Labels: 🦋 영권, Enhancement ✨, ⭐️Release Fighting⭐️, Refactor🔪
