Repository TeamSparker/Spark-Server, pull requests merged in 2022-01, with the labels that each got.

#9 [FEAT] checkUser 미들웨어 구현
  functions/api/routes/auth/authSignUpPOST.js
  functions/api/routes/auth/authTestGET.js
  functions/api/routes/auth/index.js
  functions/constants/jwt.js
  functions/constants/responseMessage.js
  functions/db/db.js
  functions/db/user.js
  functions/lib/jwtHandlers.js
  functions/middlewares/auth.js
  functions/middlewares/uploadImage.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement, 🐱 설희

#3 [FEAT] POST /room 습관 방 생성 API 구현
  functions/api/index.js
  functions/api/routes/room/index.js
  functions/api/routes/room/roomPOST.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/room.js
  functions/db/user.js
  functions/package-lock.json
  functions/package.json
Labels: 🦋 영권, enhancement, invalid

#5 [FEAT] GET /room/code/:code 참여코드로 대기방 조회 API 구현
  functions/api/routes/room/index.js
  functions/api/routes/room/roomCodeGET.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, enhancement

#16 [FIX] 참여코드로 습관방 조회 - isKicked Checking
  functions/api/routes/room/roomCodeGET.js
  functions/db/room.js
Labels: bug, 🦋 영권, enhancement

#26 [DELETE] /notice/:noticeId 알림 삭제
  functions/api/routes/notice/index.js
  functions/api/routes/notice/noticeDELETE.js
  functions/constants/responseMessage.js
  functions/db/notice.js
Labels: 🦋 영권, DELETE ❤️‍🔥, enhancement

#28 [FIX] 알림 읽음 처리 - Timezone Issue
  functions/db/notice.js
Labels: bug, 🦋 영권, enhancement

#34 [PATCH] /room/:roomId/purpose 나의 목표 설정하기
  functions/api/routes/room/index.js
  functions/api/routes/room/roomCodeGET.js
  functions/api/routes/room/roomPurposePATCH.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, enhancement, PATCH 💚

#30 [POST] /room/:roomId/enter 습관방 참여
  functions/api/routes/room/index.js
  functions/api/routes/room/roomEnterPOST.js
  functions/api/routes/room/roomPOST.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, enhancement, POST 💜

#41 [FIX] 습관 방 생성시, entry 추가 구현 누락
  functions/api/routes/room/roomCodeGET.js
  functions/api/routes/room/roomPOST.js
  functions/db/room.js
Labels: bug, 🦋 영권, enhancement

#45 [FIX] 습관 방 참여시, 입장 정원 체크 누락
  functions/api/routes/room/roomCodeGET.js
  functions/api/routes/room/roomEnterPOST.js
  functions/constants/responseMessage.js
Labels: bug, 🦋 영권

#38 [GET] /room/:roomId/waiting 대기방 조회
  functions/api/routes/room/index.js
  functions/api/routes/room/roomWaitingGET.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, enhancement, GET 🧡

#53 [FEAT] PUSH ALARM Test Code
  functions/api/routes/notice/index.js
  functions/api/routes/notice/push/index.js
  functions/api/routes/notice/push/pushTestGET.js
  functions/constants/responseMessage.js
  functions/package.json
Labels: 🦋 영권, enhancement

#57 [STYLE] date format 변경
  functions/api/routes/feed/feedGET.js
Labels: bug, 🐱 설희

#54 [POST] 스파크 보내기 API
  functions/api/routes/room/index.js
  functions/api/routes/room/roomRecordPOST.js
  functions/api/routes/room/sparkPOST.js
  functions/constants/responseMessage.js
  functions/db/record.js
  functions/db/room.js
  functions/db/spark.js
Labels: enhancement, POST 💜, 🐱 설희

#58 [POST] /room/:roomId/status 쉴래요, 고민중
  functions/api/routes/room/index.js
  functions/api/routes/room/roomStatusPOST.js
  functions/constants/alarmMessage.js
  functions/constants/responseMessage.js
  functions/db/notice.js
  functions/db/record.js
  functions/db/user.js
  functions/lib/pushAlarm.js
Labels: 🦋 영권, enhancement, POST 💜

#61 [GET] /myroom/:roomType 보관함 조회
  functions/api/routes/feed/feedGET.js
  functions/api/routes/myroom/index.js
  functions/api/routes/myroom/myroomGET.js
  functions/api/routes/room/roomDetailGET.js
  functions/api/routes/room/roomListGET.js
  functions/api/routes/room/sparkPOST.js
  functions/constants/responseMessage.js
  functions/db/room.js
  functions/db/spark.js
Labels: enhancement, GET 🧡, 🐱 설희

#66 [GET] /myroom/:roomId 특정 습관방 사진 모아보기
  functions/api/routes/myroom/index.js
  functions/api/routes/myroom/myroomGET.js
  functions/api/routes/myroom/myroomRoomGET.js
  functions/constants/responseMessage.js
  functions/db/record.js
  functions/db/spark.js
Labels: enhancement, GET 🧡, 🐱 설희

#68 [REFACTOR] 습관방 시작 roomId type checking
  functions/api/routes/room/roomStartPOST.js
Labels: 🦋 영권, enhancement

#70 [FEAT] 습관 방 시작 시, 알림 및 푸시알림 보내기
  functions/api/routes/room/roomStartPOST.js
  functions/constants/alarmMessage.js
  functions/lib/pushAlarm.js
Labels: 🦋 영권, enhancement

#76 [POST] /feed/:recordId/like 좋아요 및 좋아요 취소
  functions/api/routes/feed/feedLikePOST.js
  functions/api/routes/feed/index.js
  functions/constants/responseMessage.js
  functions/db/like.js
  functions/db/record.js
Labels: 🦋 영권, enhancement, POST 💜

#86 [FIX] 피드 모아보기 roomName 안뜨는 bug
  .github/ISSUE_TEMPLATE/feature_request.md
  functions/api/routes/feed/feedGET.js
Labels: bug, 🐱 설희

#89 [STYLE] scheduler 주석 추가
  functions/db/room.js
  functions/scheduler/funcs.js
Labels: 🐱 설희

#91 [REFACTOR] SignUP ReqBody 수정
  functions/api/routes/auth/authSignUpPOST.js
  functions/db/user.js
Labels: 🦋 영권, enhancement

#95 [FIX] 보관함 리스트 waitingRooms / ongoingRooms sort
  functions/api/routes/room/roomListGET.js
Labels: bug, GET 🧡, 🐱 설희

#98 [FIX] 대기방에 나 혼자 있을 때 버그 수정
  functions/api/routes/room/roomWaitingMemberGET.js
Labels: bug, 🐱 설희

#99 [GET] /auth/doorbell api for AppJam API 구현
  functions/api/routes/auth/authDoorbellGET.js
  functions/api/routes/auth/index.js
  functions/api/routes/room/roomCodeGET.js
  functions/api/routes/room/roomWaitingGET.js
  functions/constants/alarmMessage.js
  functions/constants/responseMessage.js
  functions/db/user.js
Labels: 🦋 영권, enhancement, GET 🧡

#106 [HOTFIX] roomGET API Bug
  functions/api/routes/room/roomDetailGET.js
Labels: bug, 🦋 영권, enhancement

#108 feat: Slack API - roomPOST
  functions/api/routes/room/roomPOST.js
Labels: 🦋 영권, enhancement

#113 [FEAT] Slack API - roomPurposePATCH
  functions/api/routes/room/roomPurposePATCH.js
Labels: 🦋 영권, enhancement

#118 [FEAT] Slack API - roomPurposePATCH
  functions/api/routes/room/roomStartPOST.js
Labels: 🦋 영권, enhancement

#120 [FEAT] Slack API - roomStatusPOST
  functions/api/routes/room/roomStatusPOST.js
Labels: 🦋 영권, enhancement

#122 [FEAT] Slack API - roomWaitingGET
  functions/api/routes/room/roomWaitingGET.js
Labels: 🦋 영권, enhancement

#124 [FEAT] Slack API - roomWaitingMemberGET
  functions/api/routes/room/roomWaitingMemberGET.js
Labels: 🦋 영권, enhancement

#126 [FEAT] Slack API - sparkPOST
  functions/api/routes/room/sparkPOST.js
Labels: 🦋 영권, enhancement

#130 feat: Slack API - feedLikePOST
  functions/api/routes/feed/feedLikePOST.js
Labels: 🦋 영권, enhancement

#101 [FIX] 방 생성한 날에 방 폭파되는 bug fix
  functions/db/room.js
Labels: bug, 🐱 설희

#132 fix: roomList 배열 순서 버그 픽스 + profileImg 2개만 뜨는 error fix
  functions/api/routes/room/roomListGET.js
Labels: bug, 🐱 설희

#133 [FEAT] 스케줄잡 slack 연결
  functions/api/routes/room/roomDetailGET.js
  functions/scheduler/funcs.js
Labels: enhancement, 🐱 설희

#134 [FEAT] 스케줄잡 cron 표현식 초 추가
  functions/scheduler/scheduler.js
Labels: enhancement, 🐱 설희

#137 [REFACTOR] /auth/doorbell response
  functions/api/routes/auth/authDoorbellGET.js
Labels: 🦋 영권, enhancement

#140 [FIX] TotalRoomNum calculation bug
  functions/api/routes/myroom/myroomGET.js
  functions/lib/dbUpdater.js
Labels: bug, 🦋 영권

#146 [SUPERSOHOTFIX] schedule DB추가로, deploy시 node-schedule 2번 도는 bug fix
  functions/db/index.js
  functions/db/schedule.js
  functions/scheduler/funcs.js
  functions/scheduler/scheduler.js
Labels: bug, 🐱 설희

#148 [REFACTOR] APPJAM 대비 Push message
  functions/api/routes/room/roomRecordPOST.js
  functions/api/routes/room/roomStatusPOST.js
  functions/constants/alarmMessage.js
Labels: 🦋 영권, enhancement

#150 [HOTFIX] roomListGET isDone response error
  functions/api/routes/room/roomListGET.js
Labels: bug, 🦋 영권, enhancement

#153 [FIX] 쉴래요 누르면 카운트 차감
  functions/api/routes/room/roomStatusPOST.js
  functions/constants/responseMessage.js
  functions/db/room.js
Labels: 🦋 영권, enhancement

#160 [FIX] 습관방 생명 차감시, room.updated_at 업데이트 하기
  functions/db/room.js
Labels: 🦋 영권, enhancement
